# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Echoer
paginate:       5
baseurl:        "/"
url:            "https://brianmcfeeley.github.io/echoer"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
theme:          tale

# About
author:
  name:         Brian McFeeley
  url:          http://example.com
  email:        brianmcfeeley@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/brianmcfeeley/echoer

# Gems
gems:
  - jekyll-paginate
